@minimalapi_HostAddress = http://localhost:5110

GET {{minimalapi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{minimalapi_HostAddress}}/checkout
Content-Type: application/json
Accept: application/json

{
    "items": [{
        "reference": "Sneaky NE2816-82",
        "name": "Sneaky",
        "quantity": 2,
        "unit": "pcs",
        "unitPrice": 2500,
        "taxRate": 1000,
        "taxAmount": 500,
        "grossTotalAmount": 5500,
        "netTotalAmount": 5000
    }],
    "amount": 5500,
    "currency": "USD",
    "reference": "demo"
}

###
POST {{minimalapi_HostAddress}}/nets/webhook
Content-Type: application/json
Authorization: authHeaderVal123

# Source: https://developer.nexigroup.com/nexi-checkout/en-EU/api/webhooks/#created
{
    "id": "458a4e068f454f768a40b9e576914820",
    "merchantId": 100017120,
    "timestamp": "2021-05-04T22:08:16.6623+02:00",
    "event": "payment.created",
    "data": {
        "order": {
            "amount": {
                "amount": 5500,
                "currency": "SEK"
            },
            "reference": "42369",
            "orderItems": [
                {
                    "reference": "Sneaky NE2816-82",
                    "name": "Sneaky",
                    "quantity": 2,
                    "unit": "pcs",
                    "unitPrice": 2500,
                    "taxRate": 1000,
                    "taxAmount": 500,
                    "netTotalAmount": 5000,
                    "grossTotalAmount": 5500
                }
            ]
        },
        "paymentId": "02a900006091a9a96937598058c4e474"
    }
}